<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Lease Agreement</title>
    <style>
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; }
        .header h1 { margin: 0; font-size: 18px; text-transform: uppercase; }
        .header p { margin: 2px 0; color: #555; }
        
        .section-title { font-weight: bold; font-size: 13px; margin-top: 20px; border-bottom: 1px solid #ddd; padding-bottom: 5px; text-transform: uppercase; }
        .content { margin-top: 10px; line-height: 1.6; text-align: justify; }
        
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        td { padding: 5px; vertical-align: top; }
        .label { font-weight: bold; width: 150px; }
        
        .signatures { margin-top: 50px; width: 100%; }
        .sign-box { width: 45%; display: inline-block; vertical-align: top; }
        .line { border-top: 1px solid #000; margin-top: 40px; width: 80%; }
    </style>
</head>
<body>

    <div class="header">
        <h1>Patani Trinidad Boarding House</h1>
        <p>Patani Road, Trinidad, Philippines</p>
        <p>Contact: 0912-345-6789 | Email: admin@patani.com</p>
    </div>

    <h2 style="text-align: center; margin-top: 20px; text-decoration: underline;">BEDSPACE LEASE AGREEMENT</h2>

    <div class="content">
        <p>This Lease Agreement is made and entered into on <strong>{{ date('F d, Y') }}</strong> by and between:</p>
        
        <p><strong>LESSOR:</strong> Cora P. Trinidad.</p>
        
        <p><strong>LESSEE:</strong> <u>{{ $booking->user->name }}</u>, of legal age, with contact number <u>{{ $booking->user->contact ?? 'N/A' }}</u>.</p>

        <div class="section-title">1. PREMISES</div>
        <p>The LESSOR hereby leases to the LESSEE a bedspace located at:</p>
        <table>
            <tr>
                <td class="label">Room Number:</td>
                <td>{{ $booking->room->room_number }} ({{ $booking->room->room_floor }})</td>
            </tr>
            <tr>
                <td class="label">Bed Number:</td>
                <td>Bed #{{ $booking->bed_number }}</td>
            </tr>
        </table>

        <div class="section-title">2. RENTAL RATE & TERM</div>
        <p>The monthly rental fee shall be <strong>₱{{ number_format($booking->room->rent_fee, 2) }}</strong>. The lease term shall commence on <strong>{{ \Carbon\Carbon::parse($booking->created_at)->format('F d, Y') }}</strong>.</p>

        <div class="section-title">3. HOUSE RULES</div>
        <p>The LESSEE agrees to abide by the following rules:</p>
        <ul>
            <li><strong>Curfew:</strong> The main gate is locked at 10:00 PM.</li>
            <li><strong>Visitors:</strong> Visitors are allowed only in the receiving area and not inside the bedrooms. No overnight visitors allowed.</li>
            <li><strong>Cleanliness:</strong> The LESSEE must maintain the cleanliness of their assigned bed and common areas.</li>
            <li><strong>Utilities:</strong> Water and Electricity charges are computed based on sub-meter readings/head count.</li>
            <li><strong>Prohibitions:</strong> No smoking, gambling, or illegal drugs inside the premises.</li>
        </ul>

        <div class="section-title">4. TERMINATION</div>
        <p>The LESSOR reserves the right to terminate this contract immediately upon violation of any house rules or failure to pay rent for one (1) month.</p>
    </div>

    <div class="signatures">
        <table style="width: 100%;">
            <tr>
                <td style="text-align: center;">
                    <div class="line"></div>
                    <strong>{{ strtoupper($booking->user->name) }}</strong><br>
                    <span>LESSEE (Tenant)</span>
                </td>
                <td style="text-align: center;">
                    <div class="line"></div>
                    <strong>CORA P. TRINIDAD</strong><br>
                    <span>LESSOR (Landlord)</span>
                </td>
            </tr>
        </table>
    </div>

    <div style="font-size: 10px; color: #999; text-align: center; margin-top: 50px;">
        <p>Generated by System on {{ date('Y-m-d H:i:s') }} | Ref #: {{ $booking->id }}</p>
    </div>

</body>
</html>